handle 'expected' failure fail as a pass

diff --git a/.github/workflows/integration-failure.yaml b/.github/workflows/integration-failure.yaml
--- a/.github/workflows/integration-failure.yaml
+++ b/.github/workflows/integration-failure.yaml
@@ -26,4 +26,11 @@ jobs:
       - name: Sleepy Time
         run: buildevents cmd $TRACE_ID $STEP_ID sleep -- sleep 1
       - name: Expected Failure
-        run: buildevents cmd $TRACE_ID $STEP_ID 'failing step' -- exit 1
+        run: |
+          buildevents cmd $TRACE_ID $STEP_ID 'failing step' -- exit 1
+          if [ $? -eq 1 ]; then
+            exit 0
+          else
+            echo "buildevent binary did not pass through expected error code"
+            exit 127
+          fi
